services:
  sobits-container:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
      network: host
      args:
        LOCAL_UID: ${LOCAL_UID}
        LOCAL_GID: ${LOCAL_GID}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        COMPUTE_TYPE: ${COMPUTE_TYPE}
        USERNAME: ${USERNAME}
        CONTAINER_NAME: ${CONTAINER_NAME}
        CUDA_VERSION: ${CUDA_VERSION}
        PYTORCH_VERSION: ${PYTORCH_VERSION}
        INSTALL_ROS: ${INSTALL_ROS}
        INSTALL_GAZEBO: ${INSTALL_GAZEBO}
        INSTALL_PYTORCH: ${INSTALL_PYTORCH}
        INSTALL_CV2: ${INSTALL_CV2}
        ROS_DISTRO: ${ROS_DISTRO}
        ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
        CV2_VERSION: ${CV2_VERSION}
        CV_IMAGE_TAG: ${CV_IMAGE_TAG}
        PYTORCH_IMAGE_TAG: ${PYTORCH_IMAGE_TAG}
        OPENCV_BASE_STAGE: ${OPENCV_BASE_STAGE}
        PYTORCH_BASE_STAGE: ${PYTORCH_BASE_STAGE}
        FINAL_STAGE: ${FINAL_STAGE}
    env_file: .env
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    privileged: true
    user: "${LOCAL_UID}:${LOCAL_GID}"
    network_mode: host
    ipc: host
    shm_size: "1g"
    stop_grace_period: 1s
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/${LOCAL_UID}/pulse/native
    devices:
      - /dev/snd
    volumes:
      - ${XDG_RUNTIME_DIR}/pulse:/run/user/${LOCAL_UID}/pulse
      - ../src:/home/${USERNAME}/colcon_ws/src
      - /dev/bus/usb:/dev/bus/usb
      - /etc/udev/rules.d/:/etc/udev/rules.d/
      - /dev/serial/by-id/:/dev/serial/by-id/
    group_add:
      - adm
      - audio
      - sudo
      - video
      - dialout
    stdin_open: true
    tty: true

  # GPU configuration with device access
  sobits-container-gpu:
    build: 
      target: final
    extends:
      service: sobits-container
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  
      - NVIDIA_DRIVER_CAPABILITIES=all  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
